---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - source.yaml
  - release.yaml
  - primerochka-bucket-setup.yaml
  - mail-backup-provisioning.enc.yaml
  - mail-backup-config.yaml
  - mail-backup-ingress.yaml
