---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neo4j
  namespace: neo4j
spec:
  interval: 5m
  chart:
    spec:
      chart: neo4j
      version: '5.x.x'
      sourceRef:
        kind: HelmRepository
        name: neo4j
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Neo4j configuration
    neo4j:
      name: "neo4j"
      # Edition: community or enterprise
      edition: "community"
      
    # Resources
    resources:
      cpu: "1000m"
      memory: "2Gi"
      
    # Storage
    volumes:
      data:
        mode: "defaultStorageClass"
        defaultStorageClass:
          requests:
            storage: "50Gi"
      logs:
        mode: "defaultStorageClass"
        defaultStorageClass:
          requests:
            storage: "1Gi"
            
    # Service configuration
    services:
      neo4j:
        enabled: true
        type: ClusterIP
        ports:
          http:
            enabled: true
            port: 7474
          bolt:
            enabled: true
            port: 7687
            
    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 7474
      runAsGroup: 7474
      fsGroup: 7474