apiVersion: v1
kind: Service
metadata:
  name: teamspeak
  namespace: teamspeak
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: teamspeak
  ports:
    - name: voice
      port: 9987
      targetPort: voice
      protocol: UDP
    - name: filetransfer
      port: 30033
      targetPort: filetransfer
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: teamspeak-query
  namespace: teamspeak
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: teamspeak
  ports:
    - name: query
      port: 10011
      targetPort: query
      protocol: TCP
