apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mail-hub
  namespace: mail-system
spec:
  secretName: mail-hub-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  usages:
    - digital signature
    - key encipherment
    - server auth
  dnsNames:
    - mx1.shanginn.io
    - mail-admin.shanginn.io
