apiVersion: v1
kind: ServiceAccount
metadata:
  name: stalwart
  namespace: mail-system
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mail-reconciler
  namespace: mail-system
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mail-backup
  namespace: mail-system
automountServiceAccountToken: false
