apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: temporal-basic-auth
  namespace: kube-system
spec:
  basicAuth:
    secret: temporal-basic-auth
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: temporal-redirect-https
  namespace: kube-system
spec:
  redirectScheme:
    scheme: https
    permanent: true
