apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: talk-to-work
  namespace: talk-to-work
spec:
  secretName: talk-to-work-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  usages:
    - digital signature
    - server auth
  dnsNames:
    - talk-to-work.rubase.shanginn.io
