apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: talk-to-work
  namespace: talk-to-work
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: talk-to-work-edge-rate-limit@kubernetescrd,talk-to-work-edge-auth@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - secretName: talk-to-work-tls
      hosts:
        - talk-to-work.rubase.shanginn.io
  rules:
    - host: talk-to-work.rubase.shanginn.io
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: talk-to-work-bridge
                port:
                  name: http
