apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: talk-to-work
resources:
  - namespace.yaml
  - service.yaml
  - endpoint-slice.yaml
  - certificate.yaml
  - middleware.yaml
  - ingress.yaml
  - basic-auth.enc.yaml
