apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: temporal-grpc-tls
  namespace: temporal
spec:
  secretName: temporal-grpc-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  usages:
    - digital signature
    - key encipherment
    - server auth
  dnsNames:
    - temporal-grpc.rubase.shanginn.io
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: temporal-grpc
  namespace: temporal
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`temporal-grpc.rubase.shanginn.io`)
      services:
        - name: temporal-authenticated-frontend
          port: grpc-rpc
  tls:
    passthrough: false
    secretName: temporal-grpc-tls
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: temporal-authenticated-frontend-from-traefik
  namespace: temporal
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: temporal
      app.kubernetes.io/instance: temporal
      app.kubernetes.io/component: frontend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - port: 7233
          protocol: TCP
