apiVersion: v1
kind: Secret
metadata:
    name: meilisearch
    namespace: temporal
    labels:
        app.kubernetes.io/name: meilisearch
        app.kubernetes.io/part-of: temporal
type: Opaque
stringData:
    master-key: ENC[AES256_GCM,data:XDpxO4agWU0VKktTIxWbwsoQA21MklXVSb0FT2y9y/oZE12tDC214B/Aitcis9pnWSL1hzzaPdZ620pkkXo4HQ==,iv:IePLLB9oEgSxvEKZ2gE1A/zD65ttI4VTYXzqsxbKlmQ=,tag:3oo03CWNEiyx/pzRRDzidg==,type:str]
sops:
    age:
        - recipient: age16qyyuegxwzgwytee9u0fw477zjq4pt5plt877rw45qcx2yl5nujske0fu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZ2Z2ZTV0TW14RVpIVHls
            K1dvZVcwS1ZkVlhyZGNPSkpxQUE0Mk80MUU4ClpWaHUyem5wZ3NiRWFjWVVhYWl0
            ODlYSXNwOWtveTlTVFN1ZXRBRW1QblUKLS0tIG5HNW9GT0JrZnBEWEZTV3o4ZGI2
            dFN2ZHR4ZmdCSlU0dU5xNVppNG5sRkEKIHOmr45rXGOr6NUZjr9mLJ+/zsZ2BVw3
            7IrnW+teM+lVOsmmzHqSFi6Lgnk/9QXyCnzod/9NHFzLiyta96J1/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-28T11:52:41Z"
    mac: ENC[AES256_GCM,data:aD0tMKCVB+SO/a7q1iH6gdRtHWqrTMiMa7+12gHCF5Mr1Ebc985Oh8XsxqFb/8YdENMnq91vtMwwJHymrp7Gh8L+knt7jjhInpsoV3U5v/wpBNMM3TamAgQacPnt54NXJg0BfF64RcopDTiXVatwxVue6ud0A9A9xNlp9iCmWr4=,iv:GsOcgQf75lhmmWNX85xm7nLRTJrTCXtPLxLcbTwzrTs=,tag:Q+C1ZHZEDlQOX+Kl6SBoyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
