apiVersion: batch/v1
kind: Job
metadata:
  name: temporal-namespace-setup
  namespace: temporal
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: temporal-cli
          image: temporalio/admin-tools:1.29.1-tctl-1.18.4-cli-1.5.0
          env:
            - name: TEMPORAL_CLI_ADDRESS
              value: "temporal-frontend:7233"
            - name: NAMESPACES
              value: "primerochka,genera4" # Comma separated list of namespaces
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Waiting for Temporal Frontend..."
              until tctl cluster health | grep -q "SERVING"; do
                echo "Waiting for temporal..."
                sleep 5
              done

              IFS=',' read -ra NS_LIST <<< "$NAMESPACES"
              for ns in "${NS_LIST[@]}"; do
                echo "Registering '$ns' namespace..."
                tctl --namespace "$ns" namespace register --retention 3 || true
              done
              
              echo "Done!"
