apiVersion: v1
kind: Secret
metadata:
    name: temporal-local-auth-oidc
    namespace: temporal
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:BXUIuMUFL3LWoiHkZOHTd9hfKlOi5IR5lGkTs7z0CIQyoApr8KtJn2dtpnz7ohCx+NeFcw+CLYzXNiEWq1NkYd3NG7gQHRsptaO7lp0b6e6lM3or3qy2TA8jw2v/cJX7,iv:0Kianjdq6xVrTKE2pRZm7qIeOwYOKu9YXoLlj10y3Dw=,tag:Dy9Ejw4hptId+HJtPzSsMg==,type:str]
sops:
    age:
        - recipient: age16qyyuegxwzgwytee9u0fw477zjq4pt5plt877rw45qcx2yl5nujske0fu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WTRuZ0t0WGNXNHEvS3Zl
            ZmtTTGRuSWFCeW1vUHRqM0VnNnA3UUdXamxjClk5cERmb24reFozSlZMd1dtT3Zq
            cmg2dkxiNTZvQTcxSUVOc1hnME1na1kKLS0tIDh1QzM0c0lsOHJGSEtDSXBtVGU1
            eEpBeGxwWXpadW8zazhiTWxWR0libjQKtcAF6ngugpF4puD71D383BIhJrmfhgqo
            4XHHBNCT4cY8kJL2JfoI8pIWNQjhoLqnXjCEW0AtJD1JrIkciskCBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-28T17:00:04Z"
    mac: ENC[AES256_GCM,data:UtY+Ci59rLBSX5ONx14l697mdkX66Dw9EvQdfdg/RFVu9o4tZgzOZojET3tSdz036N9ZVdHKyWjUMSFnGFdTvmC5cHbG83WzFwv//bbG9U5Dv9o9ntxvVHmqKOAQCfovVq96npUNgIJ/G/n9/BhEM1R/NoRCsfMIIdf4k/ZfRTM=,iv:xo0rqBHHZB6txjUXutDCUkiP7ZoMq4HQRqr6IRMCHOY=,tag:WKFbwuBe+0ukZU++A2MEQg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
