apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: temporal
  namespace: temporal
spec:
  interval: 1h
  chart:
    spec:
      chart: temporal
      version: "0.72.0"
      sourceRef:
        kind: HelmRepository
        name: temporal
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    serviceAccount:
      create: true
      name: "temporal"
    server:
      replicaCount: 1
      config:
        numHistoryShards: 512
        persistence:
          default:
            driver: "sql"
            sql:
              driver: "postgres12"
              host: "main-db-rw.database.svc.cluster.local"
              port: 5432
              database: "temporal"
              user: "temporal_user"
              password: "" # Password managed by secret
              existingSecret: "temporal-db-user"
              maxConns: 20
              maxConnLifetime: "1h"
          visibility:
            driver: "sql"
            sql:
              driver: "postgres12"
              host: "main-db-rw.database.svc.cluster.local"
              port: 5432
              database: "temporal_visibility"
              user: "temporal_user"
              password: "" # Password managed by secret
              existingSecret: "temporal-db-user"
              maxConns: 20
              maxConnLifetime: "1h"
    schema:
      createDatabase:
        enabled: true
      setup:
        enabled: true
      update:
        enabled: true
    admintools:
      enabled: true
    web:
      enabled: true
      ingress:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.middlewares: kube-system-temporal-basic-auth@kubernetescrd
        hosts:
          - "temporal.shanginn.io"
        tls:
          - secretName: temporal-tls
            hosts:
              - "temporal.shanginn.io"
    elasticsearch:
      enabled: false
    prometheus:
      enabled: false
    grafana:
      enabled: false
    cassandra:
      enabled: false
