apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.26"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  targetNamespace: cnpg-system
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace