apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdd-local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-hdd-pv
spec:
  # 935Gi maximizes your 937GB drive (leaving 2GB for FS overhead)
  capacity:
    storage: 935Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hdd-local
  local:
    path: /mnt/storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "dedic140"