apiVersion: v1
data:
    access-key: ENC[AES256_GCM,data:1aX8yDdm4nhP2tDvIhZ8/AszFl80n35B,iv:3/n7hF8m+53mlKd5SQAg53pNo8j4HUfwjjKwq0dc67o=,tag:VH/NWcgn1lF+tFkMgx6PTw==,type:str]
    bucket: ENC[AES256_GCM,data:e47WRBl36QT6Yx9k,iv:VLCy9nfijaIl9tW+KuQwnIOLMMTYrXV9Olz1fn5N784=,tag:47sM9mCK3IwgM6zjf7CKKw==,type:str]
    endpoint: ENC[AES256_GCM,data:3JmuFRaYldLGqXMzYEBwY4XyKAS9WNQH4glo0WJP/upMDAwqXUnXuqYeaU4=,iv:MCXnIAcxkolGbZP8luXEAkgRHTQeBWWcRHU6fTWnnj0=,tag:fowlIdQ/+IPRNSuhrHqVEQ==,type:str]
    restic-password: ENC[AES256_GCM,data:tIQ6xBgbumdAKb6WNFkhZf/FFzvUQikc+Ng5XcpOqFq8LFyAA6rpSyj82syzxxNiIlfjlC7FoYKn/hUO5zAS5w==,iv:rgki6ycL3ZsV6wGbWqen/RinRPjNm30wjnCp1TAPQdQ=,tag:HaE4cpb+0vOfEIcjGvzHsw==,type:str]
    secret-key: ENC[AES256_GCM,data:BsMx2/h1yg+xhJptF4Gmxblw4sQ4v+hNs4p0cq3GgKyZ3LLAgI4dEIcdIlIS+T1Eux3PL3qjS5WIh94e3Qa9FA==,iv:r4wvta/skk/3FaFb5EznF/QMbUt6enVwkWDb+vd/4vY=,tag:8VMdRQSfT69e+5CXiXMbRg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: mail-backup-credentials
    namespace: mail-system
sops:
    age:
        - recipient: age16qyyuegxwzgwytee9u0fw477zjq4pt5plt877rw45qcx2yl5nujske0fu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyd3duMjRQRFhLOU5CTWNG
            cmpjQXBnYzYyd2lReW53b1JoN3lzcG9Kd2d3CkFXNTlhcEpUWGE1b0dMOUFXUEYr
            SmVhSDBzUWkxdC9vZE96dFpQa09ibkUKLS0tIDBTZWJIUEJNdlFrc3BwL2tNQkFJ
            cVNJZVluVTFTRjRmSXR3MEhHYTJrOXcKDJt15ldbJbOCzS3RNfAHECDJHaHodMxq
            TayC/a0Cw7U+3VmDAnvAbzMS1XgVhvHWP4hlx15hx9nz9bCQrAkAiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-17T06:56:35Z"
    mac: ENC[AES256_GCM,data:SgRypJZm1yRTUMQ7Uzp+shWHrT9vCrvx6r8uLQpUz1cqmTY39yk9g63U3FMYyPUEKfThgU1kiV58cHfaE8ZEI5i7YjCWXN62MpEgs8M+DWgwzQrC+FGM/sIyYUmWi0mpQ0egTEx7JsVQP1YLhHYi5zZW1m6n0Wl0wdBLic2dVWM=,iv:tKH538WTVOn6dQAi8l8f9ZpUzmKimcb4Mzy7tmuKjVY=,tag:e/AVYmJJgxg0y/u74qaGKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
