apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:qrYBiuK/hwm+kJmTbGpjXZ6LHgfaHyL2FIrVT6N8ayD2HwKzJMZlV6lioqoERarNyENSnepZFW9E86uCFrTqDQ==,iv:twP5GF/H0UGE4hcmAFivxOwfgZylCfeyoCV0fOWxgZY=,tag:EclAWz0l4Kdt080Yacq9oQ==,type:str]
    gitops-password: ENC[AES256_GCM,data:7IkCsEufPjLezcQzzcPmAeOUFYz3lcIvIosp3ttu7M6tj+chSiWSrcFy2H1t035k7Kins6kk+iGdyJjt0ZwTww==,iv:1ftERxOpO9Wcr61RyPEth+3YhoCDT7llivzQn1vvBA8=,tag:JQZ7dTr0bDBdBYdj/Mmirg==,type:str]
    metrics-password: ENC[AES256_GCM,data:yxbqm2iOHsgYQMsbEQ/5/xaD6xZ4w4dZX0HWG4tTXkWcDwx7XLSLIyIfv5VHqKTVgCnCd8c5Y3Gmy2xNQkFeKg==,iv:X0n5MU5akO9uoxsObYeupDFmRnEXxJ1Ox2RLsurH6h0=,tag:7Yg64CrV0f1IvwjozDnijg==,type:str]
    metrics-username: ENC[AES256_GCM,data:kRg0YMmilalmVpN4PjibW24/ch4=,iv:VuSppJn25/1Ri0+OG+BxY7kX5InFZYRdhFUOfBSfbz8=,tag:kff0RoH/6+AONxNa1WNGoQ==,type:str]
    vibesites-hello-password: ENC[AES256_GCM,data:1iLTIrHMj/qy9v4EwcDmPMgPU79b7AarRRTIpEhRW5hMlfvD0TDDLPNJ87Tz1BxZZ2i8o8Mz6nbr9KdBPiY9E9WgQrhzUNliEAT/43CIknTMg5x8yZbhz2qqy2uEne79,iv:umY0wx0CVV4eFIensSlg8swZ3k97+60724hgxxU7jsk=,tag:YaVI4tjxdOgw7VJFgyksEA==,type:str]
    admin-allowed-ips: ENC[AES256_GCM,data:Ke65ynjcysQa8Uh/FU38mtrbVXvWPmV4HE7aGQ86171XrLok,iv:tpmLvc2fNP1LxgFixcAzr8MqoYd5Uasa7O1CoxOicjw=,tag:tOfwwcTnMcxqWegr5iVVzw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: mail-system-credentials
    namespace: mail-system
sops:
    age:
        - recipient: age16qyyuegxwzgwytee9u0fw477zjq4pt5plt877rw45qcx2yl5nujske0fu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIY0tqMFVsaHlJOUVOVFVF
            aUpoSXlYWnhEWGRhdVJ1ellUQ29ZSVJsdFhrClUzcW5qbE05VXJqWENzZ3BWTWhZ
            OUdJMkZCNVcvYVVyUmxUQm5OYXVaYmMKLS0tIHIyYTZlbmtrVlhhTHVVMTZLUXdl
            U2xiRFZEU1dCdkgxN1N3ZkVMUmhKaFEKmMCAquMYWX9ZIaDhsYv9t4+cPJGnH/7c
            CL6K5gvgKEBhnISlROw3gRaEZ/ZKbhZERn7aqzez+R3/AtjCPYN3Tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T04:41:55Z"
    mac: ENC[AES256_GCM,data:cCa8CelXMKbDmjt5s8xXGbBy+GwPHGTw4IsxfpD4OgkceLwsUy5MzsWKykhGZtLCNAAPoU3nOlclFtFyWylNMWWRZjDmR1h7a6Z5booBUEtiQqVkEruLmfTzv3aMlc8VCaDatnM7YKSm+3FXM+2achcqnPt7jdkEblMaauU4y1I=,iv:ejJYA9GW4sqSmi4jqtxPPN5QPiaRWu2O06G27XJMmdU=,tag:6MzY34P+3keV4qXavM09Gw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
