---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: redis
spec:
  chartRef:
    kind: OCIRepository
    name: dragonfly
    namespace: flux-system
  interval: 1m
  values:
    prometheusRule:
      enabled: true
      spec:
      - alert: DragonflyMissing
        annotations:
          description: Dragonfly is missing
          summary: Dragonfly is missing
        expr: absent(dragonfly_uptime_in_seconds) == 1
        for: 0m
        labels:
          severity: critical
    extraArgs:
      - --maxmemory=8gb
    storage:
      enabled: true
      requests: 12Gi
