---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: redis
spec:
#  chart:
#    spec:
#      chart: dragonfly
#      reconcileStrategy: ChartVersion
#      sourceRef:
#        kind: HelmRepository
#        name: dragonfly
#      version: v1.22.2
  chartRef:
    kind: OCIRepository
    name: dragonfly
    namespace: flux-system
  interval: 1m
  values:
    podSecurityContext:
      fsGroup: 2000
    prometheusRule:
      enabled: true
      spec:
      - alert: DragonflyMissing
        annotations:
          description: Dragonfly is missing
          summary: Dragonfly is missing
        expr: absent(dragonfly_uptime_in_seconds) == 1
        for: 0m
        labels:
          severity: critical
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
#    serviceMonitor:
#      enabled: true
    storage:
      enabled: true
      requests: 1024Mi
