---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dragonfly
  namespace: flux-system
spec:
  interval: 1m
  type: oci
  url: oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly
