apiVersion: v1
kind: Service
metadata:
  name: vibesites-dnsdist-test
  namespace: vibesites-dns
spec:
  type: NodePort
  ports:
    - name: dns-tcp
      nodePort: 30054
      port: 53053
      protocol: TCP
      targetPort: dns-tcp
    - name: dns-udp
      nodePort: 30054
      port: 53053
      protocol: UDP
      targetPort: dns-udp
