apiVersion: v1
kind: Service
metadata:
  name: vibesites-dnsdist
  namespace: vibesites-dns
spec:
  type: NodePort
  ports:
    - name: dns-tcp
      nodePort: 30053
      port: 53
      protocol: TCP
      targetPort: dns-tcp
    - name: dns-udp
      nodePort: 30053
      port: 53
      protocol: UDP
      targetPort: dns-udp
