apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coredns
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/rubase/coredns
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  force: true
