apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: ">=0.28.x"
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
      interval: 1m
  values:
    # Enable conversion of Prometheus CRDs (ServiceMonitor, etc.)
    victoria-metrics-operator:
      operator:
        disable_prometheus_converter: false
        enable_converter_ownership: true
    
    grafana:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.shanginn.io

    vmsingle:
      enabled: true
      spec:
        retentionPeriod: "7d"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

    # Disable heavy components if not needed
    alertmanager:
      enabled: false
    vmalert:
      enabled: false
