apiVersion: v1
kind: Service
metadata:
  name: vibesites-dnsdist-test
  namespace: vibesites-dns
spec:
  type: ClusterIP
  externalIPs:
    - 185.221.212.224
  ports:
    - name: dns-tcp
      port: 53053
      protocol: TCP
      targetPort: dns-tcp
    - name: dns-udp
      port: 53053
      protocol: UDP
      targetPort: dns-udp
