apiVersion: v1
kind: Service
metadata:
  name: bind9-service
  namespace: bind9
spec:
  type: ClusterIP
  externalIPs:
    - 185.221.212.224
  ports:
    - name: bind9tcp
      port: 53
      protocol: TCP
      targetPort: bind9tcp
    - name: bind9udp
      port: 53
      protocol: UDP
      targetPort: bind9udp
