apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../components/bind9/base

patches:
  - path: service-nodeport-patch.yaml
  - path: bind9-configs-secondary-patch.yaml
    target:
      kind: ConfigMap
      name: bind9-configs
