apiVersion: v1
kind: Service
metadata:
  name: bind9-service
  labels:
    app: bind9
    app.kubernetes.io/instance: bind9
    app.kubernetes.io/name: bind9
    app.kubernetes.io/part-of: bind9
spec:
  type: ClusterIP
  selector:
    app: bind9
    app.kubernetes.io/instance: bind9
    app.kubernetes.io/name: bind9
  ports:
    - name: bind9tcp
      port: 53
      protocol: TCP
      targetPort: bind9tcp
    - name: bind9udp
      port: 53
      protocol: UDP
      targetPort: bind9udp
